name: Pytest Win

on:
  push:
    branches-ignore:
      - '**-coverage-report'
  pull_request:

jobs:
  run:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8, 3.9 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.parser-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.parser-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: pytest
        run: |
          python3 -m pip install --upgrade -e .
          cd ./pytest
          python -m pytest -q
