name: Valgrind C check
on:
  push:
    branches-ignore:
      - '**-coverage-report'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Valgrind
        run: |
          sudo apt install -y valgrind
